### ISSUE TITLE
Post event calls

### ISSUE THREAD

**Issue by ChialiT** [Unirep/explorer#1]
Explorer will use the event from protocol to post data to FE, 
https://unirep.io/docs/contracts-api/unirep-sol#events

Please research, study how to integrate these to FE.

**Comment by CJ-Rose** [comment]
@vimwitch I need some help please to understand how the front end can can communicate with the synchronizer. I have the initial UI built out and I have spent a lot of time digging into the rest of the repo but am currently stuck here. I've been referencing `create-unirep-app` repo as example of how to pull event data into the FE; it's been helpful but also creating confusion as the two repos are set up so differently.

In `create-unirep-app` the FE creates a `userContext` with a new `UserState`, then retrieves the data it needs by calling methods on that `userContext` that in turn call methods on `UserState`.
1. is this accurate?
2. `Synchronizer` is a subclass of UserState. Does this mean that the Explorer app would use a `Synchronizer` instance in the same way that `create-unirep-app` uses a `UserState` instance? 
3. `create-unirep-app` imports `UserState` into `frontend/src/contexts/User` from `node_modules` with @unirep/core.. Explorer includes it's own version of a synchronizer in `backend/src/singletons/Synchronizer` and creates a `Synchronizer` instance in `backend/src/index`
a. Do I want to call all the info from the synchronizer on this instance in `backend/src/index`? If so, I don't think I see where the FE can get it from.
b. Or should I create a `Synchronizer` in `frontend/src/contexts/info` and get that data by creating methods on class `Info` in the same way that `create-unirep-app` gets data into the `userContext` from `UserState`?
c. I have experimented with both of these options but not getting anywhere bc I'm bumping up against pieces I don't understand in multiple directions.

**Comment by vimwitch** [comment]
Right, good questions.

> is this accurate?

Yes. In `create-unirep-app` we're bootstrapping an application that will build the unirep state from the blockchain on the frontend. We do that because a user has to build state themselves to make proofs. But in the block explorer the user won't be making proofs (because it's read only) and so we don't need to build the user state in the frontend.

My thought is we synchronize only on the backend, and build a database of events stored in a way that is easily accessible. The the frontend gets the events using a simple rest API. Something like `/api/:attesterId/attestations`, `/api/:attesterId/epochs`, etc.

> Synchronizer is a subclass of UserState.

Other way around, Synchronizer is a superclass of UserState.

> Does this mean that the Explorer app would use a Synchronizer instance in the same way that create-unirep-app uses a UserState instance?

If you're talking about the backend, yes. I have a custom synchronizer implementation in the explorer backend that will listen to events for all attesters. In `@unirep/core` the synchronizer can only listen for events from 1 attester. This is something we'll change in `@unirep/core` so that the explorer doesn't need it's own synchronizer implementation.

> Question 3

None of a/b/c. No synchronizer/userstate on the frontend. It will be closer to a traditional rest API.

**Comment by CJ-Rose** [comment]
@vimwitch thank you this clears up much confusion!

My docs PR is still open, shall I add an edit for this?

<img width="1206" alt="Screen Shot 2022-12-30 at 7 32 42 PM" src="https://user-images.githubusercontent.com/79813968/210122619-ab0d09c4-01ce-4498-afbd-20d525a55622.png">

**Comment by vimwitch** [comment]
Yes, nice catch. You can include it in the PR you have open, or make another, up to you.
